### ISSUE TITLE
question

### ISSUE THREAD

**Issue by remb0** [WJ4IoT/Sunscreen#2]
I think I start over and use your logic as base (mine is too complicated now).

can you share the code for set binary_sensor.sunscreen_criteria ?
I think you created a helper (don't know which one) and a template to set that helper.

what I want to add after this is:
- simulation mode
- notifications 
- putting all validates and actual values in a google spreadsheet to debug
- extra sensor data:  temperature inside/outside/irradiance

**Comment by WJ4IoT** [comment]
binary_sensor.sunscreen_criteria = just in the UI "create helpers" select group etc
(see also one image in this project)
I also use a _critical binary sensor when instant action is required (rain, wind)
simulation mode = available (in my project "sunscreen_status" has becomes obsolete and can be used for this
debugging = I use traces in automation (btw the automation is now less triggered due to the grouping)
extra sensor = add one binary sensor in your template.yaml (or mine) or replace an existing one and add this sensor to the grouping sensor 

PS If you do not see 20 variations in create helper consider upgrade HA

**Comment by remb0** [comment]
did not know that option.   thank you very much for all comments :)
but the non critical contains also  the rain and wind?

**Comment by WJ4IoT** [comment]
> but the non critical contains also the rain and wind?

Yes, think this way it will also reduce the complexity of your automation; i.e it only requires an instant reaction to close, to open you might want to delay this to avoid your sunscreen goes to frequently open/close
